queryList = [

    {"command": "testing", "action": "test()"},
    {"command": "wikipedia", "action": "search_wikipedia()"},
    {"command": "search on youtube", "action": "search_youtube()"},
    {"command": "open youtube", "action": "open_youtube()"},
    {"command": "close chrome", "action": "close_chrome()"},
    {"command": "open google", "action": "open_google()"},
    {"command": "close google", "action": "close_google()"},
    {"command": "play music", "action": "play_music()"},
    {"command": "play iron man movie", "action": "play_ironman_movie()"},
    {"command": "close movie", "action": "close_movie()"},
    {"command": "time", "action": "get_current_time()"},
    {"command": "shutdown system", "action": "shutdown_system()"},
    {"command": "restart system", "action": "restart_system()"},
    {"command": "lock system", "action": "lock_system()"},
    {"command": "open notepad", "action": "open_notepad()"},
    {"command": "close notepad", "action": "close_notepad()"},
    {"command": "open command prompt", "action": "open_command_prompt()"},
    {"command": "close command prompt", "action": "close_command_prompt()"},
    {"command": "open camera", "action": "open_camera()"},
    {"command": "go to sleep", "action": "go_to_sleep()"},
    {"command": "take screenshot", "action": "take_screenshot()"},
    {"command": "calculate", "action": "calculate()"}
]
